version: '3'
services:
  db:
    image: postgres:13
    container_name: todoapp.postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PASS: "${DB_PASSWORD}"
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data